//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiztalkEnchereOrchestration.ServiceEnchereReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DemandeCreationEnchere", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DemandeCreationEnchere : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomEnchereField;
        
        private decimal PrixMinimumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OptionTransportField;
        
        private int DureeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeEnchereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategorieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotsClesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutresInformationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomEnchere {
            get {
                return this.NomEnchereField;
            }
            set {
                if ((object.ReferenceEquals(this.NomEnchereField, value) != true)) {
                    this.NomEnchereField = value;
                    this.RaisePropertyChanged("NomEnchere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal PrixMinimum {
            get {
                return this.PrixMinimumField;
            }
            set {
                if ((this.PrixMinimumField.Equals(value) != true)) {
                    this.PrixMinimumField = value;
                    this.RaisePropertyChanged("PrixMinimum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OptionTransport {
            get {
                return this.OptionTransportField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionTransportField, value) != true)) {
                    this.OptionTransportField = value;
                    this.RaisePropertyChanged("OptionTransport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Duree {
            get {
                return this.DureeField;
            }
            set {
                if ((this.DureeField.Equals(value) != true)) {
                    this.DureeField = value;
                    this.RaisePropertyChanged("Duree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TypeEnchere {
            get {
                return this.TypeEnchereField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeEnchereField, value) != true)) {
                    this.TypeEnchereField = value;
                    this.RaisePropertyChanged("TypeEnchere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Categorie {
            get {
                return this.CategorieField;
            }
            set {
                if ((object.ReferenceEquals(this.CategorieField, value) != true)) {
                    this.CategorieField = value;
                    this.RaisePropertyChanged("Categorie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MotsCles {
            get {
                return this.MotsClesField;
            }
            set {
                if ((object.ReferenceEquals(this.MotsClesField, value) != true)) {
                    this.MotsClesField = value;
                    this.RaisePropertyChanged("MotsCles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string AutresInformations {
            get {
                return this.AutresInformationsField;
            }
            set {
                if ((object.ReferenceEquals(this.AutresInformationsField, value) != true)) {
                    this.AutresInformationsField = value;
                    this.RaisePropertyChanged("AutresInformations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEnchereReference.ServiceEnchere_NBSoap")]
    public interface ServiceEnchere_NBSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément demandeCreationEnchere de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SauvegarderDemandeCreationEnchere", ReplyAction="*")]
        BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereResponse SauvegarderDemandeCreationEnchere(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SauvegarderDemandeCreationEnchere", ReplyAction="*")]
        System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereResponse> SauvegarderDemandeCreationEnchereAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément SauvegarderEncherissementResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SauvegarderEncherissement", ReplyAction="*")]
        BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementResponse SauvegarderEncherissement(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SauvegarderEncherissement", ReplyAction="*")]
        System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementResponse> SauvegarderEncherissementAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément BannirEncherisseurGagnantResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BannirEncherisseurGagnant", ReplyAction="*")]
        BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantResponse BannirEncherisseurGagnant(BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BannirEncherisseurGagnant", ReplyAction="*")]
        System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantResponse> BannirEncherisseurGagnantAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément SauvegarderInfosPaiementResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SauvegarderInfosPaiement", ReplyAction="*")]
        BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementResponse SauvegarderInfosPaiement(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SauvegarderInfosPaiement", ReplyAction="*")]
        System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementResponse> SauvegarderInfosPaiementAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément InformerVendeurNouveauResultatResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InformerVendeurNouveauResultat", ReplyAction="*")]
        BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatResponse InformerVendeurNouveauResultat(BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InformerVendeurNouveauResultat", ReplyAction="*")]
        System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatResponse> InformerVendeurNouveauResultatAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément SauvegarderEvaluationResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SauvegarderEvaluation", ReplyAction="*")]
        BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationResponse SauvegarderEvaluation(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SauvegarderEvaluation", ReplyAction="*")]
        System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationResponse> SauvegarderEvaluationAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément AffecterEvaluationAgentResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AffecterEvaluationAgent", ReplyAction="*")]
        BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentResponse AffecterEvaluationAgent(BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AffecterEvaluationAgent", ReplyAction="*")]
        System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentResponse> AffecterEvaluationAgentAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément BannirVendeurResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BannirVendeur", ReplyAction="*")]
        BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurResponse BannirVendeur(BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BannirVendeur", ReplyAction="*")]
        System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurResponse> BannirVendeurAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SauvegarderDemandeCreationEnchereRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SauvegarderDemandeCreationEnchere", Namespace="http://tempuri.org/", Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereRequestBody Body;
        
        public SauvegarderDemandeCreationEnchereRequest() {
        }
        
        public SauvegarderDemandeCreationEnchereRequest(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SauvegarderDemandeCreationEnchereRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.DemandeCreationEnchere demandeCreationEnchere;
        
        public SauvegarderDemandeCreationEnchereRequestBody() {
        }
        
        public SauvegarderDemandeCreationEnchereRequestBody(BiztalkEnchereOrchestration.ServiceEnchereReference.DemandeCreationEnchere demandeCreationEnchere) {
            this.demandeCreationEnchere = demandeCreationEnchere;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SauvegarderDemandeCreationEnchereResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SauvegarderDemandeCreationEnchereResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereResponseBody Body;
        
        public SauvegarderDemandeCreationEnchereResponse() {
        }
        
        public SauvegarderDemandeCreationEnchereResponse(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SauvegarderDemandeCreationEnchereResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SauvegarderDemandeCreationEnchereResult;
        
        public SauvegarderDemandeCreationEnchereResponseBody() {
        }
        
        public SauvegarderDemandeCreationEnchereResponseBody(bool SauvegarderDemandeCreationEnchereResult) {
            this.SauvegarderDemandeCreationEnchereResult = SauvegarderDemandeCreationEnchereResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SauvegarderEncherissementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SauvegarderEncherissement", Namespace="http://tempuri.org/", Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementRequestBody Body;
        
        public SauvegarderEncherissementRequest() {
        }
        
        public SauvegarderEncherissementRequest(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SauvegarderEncherissementRequestBody {
        
        public SauvegarderEncherissementRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SauvegarderEncherissementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SauvegarderEncherissementResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementResponseBody Body;
        
        public SauvegarderEncherissementResponse() {
        }
        
        public SauvegarderEncherissementResponse(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SauvegarderEncherissementResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SauvegarderEncherissementResult;
        
        public SauvegarderEncherissementResponseBody() {
        }
        
        public SauvegarderEncherissementResponseBody(string SauvegarderEncherissementResult) {
            this.SauvegarderEncherissementResult = SauvegarderEncherissementResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BannirEncherisseurGagnantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BannirEncherisseurGagnant", Namespace="http://tempuri.org/", Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantRequestBody Body;
        
        public BannirEncherisseurGagnantRequest() {
        }
        
        public BannirEncherisseurGagnantRequest(BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BannirEncherisseurGagnantRequestBody {
        
        public BannirEncherisseurGagnantRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BannirEncherisseurGagnantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BannirEncherisseurGagnantResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantResponseBody Body;
        
        public BannirEncherisseurGagnantResponse() {
        }
        
        public BannirEncherisseurGagnantResponse(BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BannirEncherisseurGagnantResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BannirEncherisseurGagnantResult;
        
        public BannirEncherisseurGagnantResponseBody() {
        }
        
        public BannirEncherisseurGagnantResponseBody(string BannirEncherisseurGagnantResult) {
            this.BannirEncherisseurGagnantResult = BannirEncherisseurGagnantResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SauvegarderInfosPaiementRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SauvegarderInfosPaiement", Namespace="http://tempuri.org/", Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementRequestBody Body;
        
        public SauvegarderInfosPaiementRequest() {
        }
        
        public SauvegarderInfosPaiementRequest(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SauvegarderInfosPaiementRequestBody {
        
        public SauvegarderInfosPaiementRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SauvegarderInfosPaiementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SauvegarderInfosPaiementResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementResponseBody Body;
        
        public SauvegarderInfosPaiementResponse() {
        }
        
        public SauvegarderInfosPaiementResponse(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SauvegarderInfosPaiementResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SauvegarderInfosPaiementResult;
        
        public SauvegarderInfosPaiementResponseBody() {
        }
        
        public SauvegarderInfosPaiementResponseBody(string SauvegarderInfosPaiementResult) {
            this.SauvegarderInfosPaiementResult = SauvegarderInfosPaiementResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InformerVendeurNouveauResultatRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InformerVendeurNouveauResultat", Namespace="http://tempuri.org/", Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatRequestBody Body;
        
        public InformerVendeurNouveauResultatRequest() {
        }
        
        public InformerVendeurNouveauResultatRequest(BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InformerVendeurNouveauResultatRequestBody {
        
        public InformerVendeurNouveauResultatRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InformerVendeurNouveauResultatResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InformerVendeurNouveauResultatResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatResponseBody Body;
        
        public InformerVendeurNouveauResultatResponse() {
        }
        
        public InformerVendeurNouveauResultatResponse(BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InformerVendeurNouveauResultatResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InformerVendeurNouveauResultatResult;
        
        public InformerVendeurNouveauResultatResponseBody() {
        }
        
        public InformerVendeurNouveauResultatResponseBody(string InformerVendeurNouveauResultatResult) {
            this.InformerVendeurNouveauResultatResult = InformerVendeurNouveauResultatResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SauvegarderEvaluationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SauvegarderEvaluation", Namespace="http://tempuri.org/", Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationRequestBody Body;
        
        public SauvegarderEvaluationRequest() {
        }
        
        public SauvegarderEvaluationRequest(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SauvegarderEvaluationRequestBody {
        
        public SauvegarderEvaluationRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SauvegarderEvaluationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SauvegarderEvaluationResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationResponseBody Body;
        
        public SauvegarderEvaluationResponse() {
        }
        
        public SauvegarderEvaluationResponse(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SauvegarderEvaluationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SauvegarderEvaluationResult;
        
        public SauvegarderEvaluationResponseBody() {
        }
        
        public SauvegarderEvaluationResponseBody(string SauvegarderEvaluationResult) {
            this.SauvegarderEvaluationResult = SauvegarderEvaluationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AffecterEvaluationAgentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AffecterEvaluationAgent", Namespace="http://tempuri.org/", Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentRequestBody Body;
        
        public AffecterEvaluationAgentRequest() {
        }
        
        public AffecterEvaluationAgentRequest(BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AffecterEvaluationAgentRequestBody {
        
        public AffecterEvaluationAgentRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AffecterEvaluationAgentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AffecterEvaluationAgentResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentResponseBody Body;
        
        public AffecterEvaluationAgentResponse() {
        }
        
        public AffecterEvaluationAgentResponse(BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AffecterEvaluationAgentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AffecterEvaluationAgentResult;
        
        public AffecterEvaluationAgentResponseBody() {
        }
        
        public AffecterEvaluationAgentResponseBody(string AffecterEvaluationAgentResult) {
            this.AffecterEvaluationAgentResult = AffecterEvaluationAgentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BannirVendeurRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BannirVendeur", Namespace="http://tempuri.org/", Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurRequestBody Body;
        
        public BannirVendeurRequest() {
        }
        
        public BannirVendeurRequest(BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class BannirVendeurRequestBody {
        
        public BannirVendeurRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BannirVendeurResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BannirVendeurResponse", Namespace="http://tempuri.org/", Order=0)]
        public BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurResponseBody Body;
        
        public BannirVendeurResponse() {
        }
        
        public BannirVendeurResponse(BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BannirVendeurResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BannirVendeurResult;
        
        public BannirVendeurResponseBody() {
        }
        
        public BannirVendeurResponseBody(string BannirVendeurResult) {
            this.BannirVendeurResult = BannirVendeurResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceEnchere_NBSoapChannel : BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEnchere_NBSoapClient : System.ServiceModel.ClientBase<BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap>, BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap {
        
        public ServiceEnchere_NBSoapClient() {
        }
        
        public ServiceEnchere_NBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEnchere_NBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEnchere_NBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEnchere_NBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereResponse BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap.SauvegarderDemandeCreationEnchere(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereRequest request) {
            return base.Channel.SauvegarderDemandeCreationEnchere(request);
        }
        
        public bool SauvegarderDemandeCreationEnchere(BiztalkEnchereOrchestration.ServiceEnchereReference.DemandeCreationEnchere demandeCreationEnchere) {
            BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereRequest inValue = new BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereRequest();
            inValue.Body = new BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereRequestBody();
            inValue.Body.demandeCreationEnchere = demandeCreationEnchere;
            BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereResponse retVal = ((BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap)(this)).SauvegarderDemandeCreationEnchere(inValue);
            return retVal.Body.SauvegarderDemandeCreationEnchereResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereResponse> BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap.SauvegarderDemandeCreationEnchereAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereRequest request) {
            return base.Channel.SauvegarderDemandeCreationEnchereAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereResponse> SauvegarderDemandeCreationEnchereAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.DemandeCreationEnchere demandeCreationEnchere) {
            BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereRequest inValue = new BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereRequest();
            inValue.Body = new BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderDemandeCreationEnchereRequestBody();
            inValue.Body.demandeCreationEnchere = demandeCreationEnchere;
            return ((BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap)(this)).SauvegarderDemandeCreationEnchereAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementResponse BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap.SauvegarderEncherissement(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementRequest request) {
            return base.Channel.SauvegarderEncherissement(request);
        }
        
        public string SauvegarderEncherissement() {
            BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementRequest inValue = new BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementRequest();
            inValue.Body = new BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementRequestBody();
            BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementResponse retVal = ((BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap)(this)).SauvegarderEncherissement(inValue);
            return retVal.Body.SauvegarderEncherissementResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementResponse> BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap.SauvegarderEncherissementAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementRequest request) {
            return base.Channel.SauvegarderEncherissementAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementResponse> SauvegarderEncherissementAsync() {
            BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementRequest inValue = new BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementRequest();
            inValue.Body = new BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEncherissementRequestBody();
            return ((BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap)(this)).SauvegarderEncherissementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantResponse BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap.BannirEncherisseurGagnant(BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantRequest request) {
            return base.Channel.BannirEncherisseurGagnant(request);
        }
        
        public string BannirEncherisseurGagnant() {
            BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantRequest inValue = new BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantRequest();
            inValue.Body = new BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantRequestBody();
            BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantResponse retVal = ((BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap)(this)).BannirEncherisseurGagnant(inValue);
            return retVal.Body.BannirEncherisseurGagnantResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantResponse> BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap.BannirEncherisseurGagnantAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantRequest request) {
            return base.Channel.BannirEncherisseurGagnantAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantResponse> BannirEncherisseurGagnantAsync() {
            BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantRequest inValue = new BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantRequest();
            inValue.Body = new BiztalkEnchereOrchestration.ServiceEnchereReference.BannirEncherisseurGagnantRequestBody();
            return ((BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap)(this)).BannirEncherisseurGagnantAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementResponse BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap.SauvegarderInfosPaiement(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementRequest request) {
            return base.Channel.SauvegarderInfosPaiement(request);
        }
        
        public string SauvegarderInfosPaiement() {
            BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementRequest inValue = new BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementRequest();
            inValue.Body = new BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementRequestBody();
            BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementResponse retVal = ((BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap)(this)).SauvegarderInfosPaiement(inValue);
            return retVal.Body.SauvegarderInfosPaiementResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementResponse> BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap.SauvegarderInfosPaiementAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementRequest request) {
            return base.Channel.SauvegarderInfosPaiementAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementResponse> SauvegarderInfosPaiementAsync() {
            BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementRequest inValue = new BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementRequest();
            inValue.Body = new BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderInfosPaiementRequestBody();
            return ((BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap)(this)).SauvegarderInfosPaiementAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatResponse BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap.InformerVendeurNouveauResultat(BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatRequest request) {
            return base.Channel.InformerVendeurNouveauResultat(request);
        }
        
        public string InformerVendeurNouveauResultat() {
            BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatRequest inValue = new BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatRequest();
            inValue.Body = new BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatRequestBody();
            BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatResponse retVal = ((BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap)(this)).InformerVendeurNouveauResultat(inValue);
            return retVal.Body.InformerVendeurNouveauResultatResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatResponse> BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap.InformerVendeurNouveauResultatAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatRequest request) {
            return base.Channel.InformerVendeurNouveauResultatAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatResponse> InformerVendeurNouveauResultatAsync() {
            BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatRequest inValue = new BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatRequest();
            inValue.Body = new BiztalkEnchereOrchestration.ServiceEnchereReference.InformerVendeurNouveauResultatRequestBody();
            return ((BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap)(this)).InformerVendeurNouveauResultatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationResponse BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap.SauvegarderEvaluation(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationRequest request) {
            return base.Channel.SauvegarderEvaluation(request);
        }
        
        public string SauvegarderEvaluation() {
            BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationRequest inValue = new BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationRequest();
            inValue.Body = new BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationRequestBody();
            BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationResponse retVal = ((BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap)(this)).SauvegarderEvaluation(inValue);
            return retVal.Body.SauvegarderEvaluationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationResponse> BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap.SauvegarderEvaluationAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationRequest request) {
            return base.Channel.SauvegarderEvaluationAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationResponse> SauvegarderEvaluationAsync() {
            BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationRequest inValue = new BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationRequest();
            inValue.Body = new BiztalkEnchereOrchestration.ServiceEnchereReference.SauvegarderEvaluationRequestBody();
            return ((BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap)(this)).SauvegarderEvaluationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentResponse BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap.AffecterEvaluationAgent(BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentRequest request) {
            return base.Channel.AffecterEvaluationAgent(request);
        }
        
        public string AffecterEvaluationAgent() {
            BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentRequest inValue = new BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentRequest();
            inValue.Body = new BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentRequestBody();
            BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentResponse retVal = ((BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap)(this)).AffecterEvaluationAgent(inValue);
            return retVal.Body.AffecterEvaluationAgentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentResponse> BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap.AffecterEvaluationAgentAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentRequest request) {
            return base.Channel.AffecterEvaluationAgentAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentResponse> AffecterEvaluationAgentAsync() {
            BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentRequest inValue = new BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentRequest();
            inValue.Body = new BiztalkEnchereOrchestration.ServiceEnchereReference.AffecterEvaluationAgentRequestBody();
            return ((BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap)(this)).AffecterEvaluationAgentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurResponse BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap.BannirVendeur(BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurRequest request) {
            return base.Channel.BannirVendeur(request);
        }
        
        public string BannirVendeur() {
            BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurRequest inValue = new BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurRequest();
            inValue.Body = new BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurRequestBody();
            BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurResponse retVal = ((BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap)(this)).BannirVendeur(inValue);
            return retVal.Body.BannirVendeurResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurResponse> BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap.BannirVendeurAsync(BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurRequest request) {
            return base.Channel.BannirVendeurAsync(request);
        }
        
        public System.Threading.Tasks.Task<BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurResponse> BannirVendeurAsync() {
            BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurRequest inValue = new BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurRequest();
            inValue.Body = new BiztalkEnchereOrchestration.ServiceEnchereReference.BannirVendeurRequestBody();
            return ((BiztalkEnchereOrchestration.ServiceEnchereReference.ServiceEnchere_NBSoap)(this)).BannirVendeurAsync(inValue);
        }
    }
}
