//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VisualStudio.BizTalkProject.Generators, Version 4.0.30319.42000.
// 
namespace BiztalkEnchereOrchestration.WebServiceEnchere {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceEnchere_NBSoap", Namespace="http://tempuri.org/")]
    [Microsoft.XLANGs.BaseTypes.WebServiceUrlAttribute("http://localhost:55661/ServiceEnchere_NB.asmx")]
    public partial class ServiceEnchere_NB : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ServiceEnchere_NB() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["BiztalkEnchereOrchestration.WebServiceEnchere.ServiceEnchere_NB"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost:55661/ServiceEnchere_NB.asmx";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SauvegarderDemandeCreationEnchere", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SauvegarderDemandeCreationEnchere([System.Xml.Serialization.XmlElementAttribute(Namespace="http://EAI.DemandeCreationEnchere")] DemandeCreationEnchere demandeCreationEnchere) {
            object[] results = this.Invoke("SauvegarderDemandeCreationEnchere", new object[] {
                        demandeCreationEnchere});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSauvegarderDemandeCreationEnchere(DemandeCreationEnchere demandeCreationEnchere, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SauvegarderDemandeCreationEnchere", new object[] {
                        demandeCreationEnchere}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndSauvegarderDemandeCreationEnchere(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SauvegarderEncherissement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SauvegarderEncherissement() {
            object[] results = this.Invoke("SauvegarderEncherissement", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSauvegarderEncherissement(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SauvegarderEncherissement", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSauvegarderEncherissement(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BannirEncherisseurGagnant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BannirEncherisseurGagnant() {
            object[] results = this.Invoke("BannirEncherisseurGagnant", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBannirEncherisseurGagnant(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BannirEncherisseurGagnant", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndBannirEncherisseurGagnant(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SauvegarderInfosPaiement", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SauvegarderInfosPaiement() {
            object[] results = this.Invoke("SauvegarderInfosPaiement", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSauvegarderInfosPaiement(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SauvegarderInfosPaiement", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSauvegarderInfosPaiement(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InformerVendeurNouveauResultat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InformerVendeurNouveauResultat() {
            object[] results = this.Invoke("InformerVendeurNouveauResultat", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInformerVendeurNouveauResultat(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InformerVendeurNouveauResultat", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndInformerVendeurNouveauResultat(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SauvegarderEvaluation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SauvegarderEvaluation() {
            object[] results = this.Invoke("SauvegarderEvaluation", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSauvegarderEvaluation(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SauvegarderEvaluation", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSauvegarderEvaluation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AffecterEvaluationAgent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AffecterEvaluationAgent() {
            object[] results = this.Invoke("AffecterEvaluationAgent", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAffecterEvaluationAgent(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AffecterEvaluationAgent", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndAffecterEvaluationAgent(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BannirVendeur", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BannirVendeur() {
            object[] results = this.Invoke("BannirVendeur", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginBannirVendeur(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("BannirVendeur", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndBannirVendeur(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BiztalkEnchereSchemas.DemandeCreationEnchere")]
    public partial class DemandeCreationEnchere {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string NomEnchere;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public decimal PrixMinimum;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string OptionTransport;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public int Duree;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string TypeEnchere;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string Categorie;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string MotsCles;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string AutresInformations;
    }
}
